FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/

COPY index.html /var/www/html/
ADD ./css /var/www/html/css
ADD ./js /var/www/html/js
ADD ./img /var/www/html/img
ADD ./img/cabecalho /var/www/html/img/cabecalho
ADD ./pages /var/www/html/pages




