
--
-- Data for Name: video_curso; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (1, 'Curso gratuito Laravel 9 INTRO #1 - Introdução e instalação', 'https://www.youtube.com/embed/_h7pq2uc6e4?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '56slkfn', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (2, 'Curso gratuito Laravel 9 INTRO #2 - O comando Artisan', 'https://www.youtube.com/embed/q3TYbWaSOqY?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '0ctdJAa', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (3, 'Curso gratuito Laravel 9 INTRO #3 - Criando rotas parte 1', 'https://www.youtube.com/embed/0IX7IgqIIe0?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'iiYXb7g', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (4, 'Curso gratuito Laravel 9 INTRO #4 - Criando rotas parte 2', 'https://www.youtube.com/embed/hMZHocLHwsk?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'YD_EwYW', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (5, 'Curso gratuito Laravel 9 INTRO #5 - A camada request', 'https://www.youtube.com/embed/cAyzFcB_8Jw?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '8hxhndw', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (6, 'Curso gratuito Laravel 9 INTRO #6 - Criando controller e linkando com as rotas', 'https://www.youtube.com/embed/isChgZfN27k?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '1WRHgAj', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (7, 'Curso gratuito Laravel 9 INTRO #7 - Renderizando views', 'https://www.youtube.com/embed/Dpgv2RylSB4?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'p5jGFyT', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (8, 'Curso gratuito Laravel 9 INTRO #8 - Diretivas do blade template', 'https://www.youtube.com/embed/dxY-x6e5jPE?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'XUcEjXW', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (9, 'Curso gratuito Laravel 9 INTRO #9 - Criando layouts com blade template', 'https://www.youtube.com/embed/meaRFfy5cdI?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'khd5ret', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (10, 'Curso gratuito Laravel 9 INTRO #10 - Injetando assets (css e javascript)', 'https://www.youtube.com/embed/8M5JuB6Qgx0?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '6lAbwL9', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (11, 'Curso gratuito Laravel 9 INTRO #11 - Compilando assets (Laravel mix)', 'https://www.youtube.com/embed/j9p7jlPFvk0?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'nZDdi8d', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (12, 'Curso gratuito Laravel 9 INTRO #12 - Introdução a migrations', 'https://www.youtube.com/embed/GsMNL4P9YI4?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '16yCseO', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (13, 'Curso gratuito Laravel 9 INTRO #13 - Criando models', 'https://www.youtube.com/embed/8pcFJ4-iTBQ?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'a3fOXTt', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (14, 'Curso gratuito Laravel 9 INTRO #14 - Seeders e factories', 'https://www.youtube.com/embed/MZ7mNIft1XQ?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'wDAI1CK', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (15, 'Curso gratuito Laravel 9 INTRO #15 - Introdução ao Eloquent - Pegando registros', 'https://www.youtube.com/embed/p-vkHYfH3mc?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'zra9rVM', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (16, 'Curso gratuito Laravel 9 INTRO #16 - Introdução ao Eloquent - Salvando registros', 'https://www.youtube.com/embed/_xWj5bulbH0?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '_c-2SBQ', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (17, 'Curso gratuito Laravel 9 INTRO #17 - Introdução ao Eloquent - Atualizando registros', 'https://www.youtube.com/embed/HV14qNvrwLI?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'ZiQtRfp', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (18, 'Curso gratuito Laravel 9 INTRO #18 - Introdução ao Eloquent - Deletando registros', 'https://www.youtube.com/embed/SjQLgxwqh7k?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'vGpKFSY', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (19, 'Curso gratuito Laravel 9 INTRO #19 - Relacionamento 1 para N', 'https://www.youtube.com/embed/9ARRTSBp6P8?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'VFgjgtV', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (20, 'Curso gratuito Laravel 9 INTRO #20 - Relacionamento N para 1', 'https://www.youtube.com/embed/kdmK38Eo0ew?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'bi98d55', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (21, 'Curso gratuito Laravel 9 INTRO #21 - Relacionamento N para N', 'https://www.youtube.com/embed/7hDVuE2hXzQ?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'HhBb6z3', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (22, 'Curso gratuito Laravel 9 INTRO #22 - Validação', 'https://www.youtube.com/embed/KaivlsFU7YI?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'yEShrt_', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (23, 'Curso gratuito Laravel 9 INTRO #23 - File upload', 'https://www.youtube.com/embed/Nv6z7BFR0W0?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'wHd9rna', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (24, 'Curso gratuito Laravel 9 INTRO #24 - Paginação', 'https://www.youtube.com/embed/aW_X1OesitM?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'WWA5fRs', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (25, 'Curso gratuito Laravel 9 INTRO #25 - Projeto aula 01', 'https://www.youtube.com/embed/WUunsWINUmw?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'DrOsPRK', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (26, 'Curso gratuito Laravel 9 INTRO #26 - Projeto aula 02', 'https://www.youtube.com/embed/shAgpj2PnV8?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'dJV6Cf2', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (27, 'Curso gratuito Laravel 9 INTRO #27 - Projeto aula 03', 'https://www.youtube.com/embed/bc0gkFllAPs?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'lYd_kJq', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (28, 'Curso gratuito Laravel 9 INTRO #28 - Projeto aula 04', 'https://www.youtube.com/embed/pU3Nh3qwM8g?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'xIB_5EO', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (29, 'Curso gratuito Laravel 9 INTRO #29 - Projeto aula 05', 'https://www.youtube.com/embed/BrvTkU2T05g?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'nmDfOUg', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (30, 'Curso gratuito Laravel 9 INTRO #30 - Projeto aula 06', 'https://www.youtube.com/embed/DvxOVq97MaU?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 't0ZE_yt', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (31, 'Curso gratuito Laravel 9 INTRO #31 - Projeto aula 07', 'https://www.youtube.com/embed/doC4M22vZII?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '_JB3bru', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (32, 'Curso gratuito Laravel 9 INTRO #32 - Projeto aula 08', 'https://www.youtube.com/embed/n_0Eb0Ry1oA?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'Dv9DuC8', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (33, 'Curso gratuito Laravel 9 INTRO #33 - Projeto aula 09', 'https://www.youtube.com/embed/AsKHRRDm5cw?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', 'ek_Msia', 2, '2024-07-08 21:50:42.80821', NULL, NULL);
INSERT INTO public.video_curso (id, titulo, url, imagem, codigo, id_grupo, created_at, updated_at, deleted_at) VALUES (34, 'Curso gratuito Laravel 9 INTRO #34 - Projeto aula 10', 'https://www.youtube.com/embed/yB7_iPjqGJQ?list=PLcoYAcR89n-reidRFA3XCIvQPeKFt4dQU', 'https://purr.objects-us-east-1.dream.io/i/OoNx6.jpg', '74kxqmy', 2, '2024-07-08 21:50:42.80821', NULL, NULL);

